on:
  - push
  - pull_request
name: CI
jobs:
  spectralChecks:
    name: Spectral checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test this action against an incorrect file.
        run: spectral lint test-sample.json

      - if: ${{ failure() }}
        run: exit 0