on:
  - push
  - pull_request
name: CI
jobs:
  spectralChecks:
    name: Spectral checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test this action against an incorrect file.
        run: docker run --rm -v ${{ github.workspace }}:${{ github.workspace }} stoplight/spectral lint ${{ github.workspace }}/test-sample.yaml --ruleset ${{ github.workspace }}/.spectral.yaml

      - if: ${{ failure() }}
        run: exit 0